### ISSUE TITLE
Error on startup / Windows 10:  CAS policy

### ISSUE THREAD

**Issue by Swiftnesses** [derwish-pro/MyNetSensors#13]
Hello,

I get this when trying to start the latest version on Windows 10 x64.

Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web, localhost, ef.
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
Press any key to continue . . .

**Comment by dy-sh** [comment]
http://mynodes.net/Software/Troubleshooting#cas-policy

**Comment by Swiftnesses** [comment]
Yes, I'm an idiot. Fixed :-)

**Comment by Swiftnesses** [comment]
The issue is, it pegs my cpu at 50%, known issue?

http://postimg.org/image/tn7wkoidp/

**Comment by dy-sh** [comment]
I added a few thousand nodes in the scene. CPU load is small.

**Comment by dy-sh** [comment]
Try to observe in which case the CPU is loaded.

**Comment by Swiftnesses** [comment]
I have 1 node, fresh install, seems to peg at 50%... Tried a reboot etc.

**Comment by dy-sh** [comment]
I have no idea what it could be. Try to run fresh copy of the program in a new folder. In the wizard, refuse usage of the database and the gateway. Skip those steps. Look, will this have any effect.

**Comment by dy-sh** [comment]
Try this cpu usage fix.
In nodesEngine.cs

 private void UpdateNodesLoop()
        {
            Task.Run(() =>
            {
                while (true)
                {
                    **Thread.Sleep(10);**
                    if ((DateTime.Now - lastUpdateTime).TotalMilliseconds < updateInterval)
                        continue;

**Comment by bkrajendra** [comment]
I was stuck on this CAS issue for almost 15 days. tried everything but no solution. Finally found that setting "Unblock" on individual files may solve this. Hence used a PS command to do it recursively on entire files n folders:
```
dir -Recurse | Unblock-File
```
make sure you are inside MyNodes folder.
